"""partner_id added to applications table

Revision ID: 76fe541e9e3a
Revises: e318b087e875
Create Date: 2024-06-25 16:16:06.889313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76fe541e9e3a'
down_revision: Union[str, None] = 'e318b087e875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'applications', 'partners', ['partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'partner_id')
    # ### end Alembic commands ###
