"""on delete cascade

Revision ID: 80b795b9f0d2
Revises: fb7ad862d12c
Create Date: 2024-06-26 16:01:56.086864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b795b9f0d2'
down_revision: Union[str, None] = 'fb7ad862d12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('application_clients_application_id_fkey', 'application_clients', type_='foreignkey')
    op.drop_constraint('application_clients_client_id_fkey', 'application_clients', type_='foreignkey')
    op.create_foreign_key(None, 'application_clients', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'application_clients', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application_clients', type_='foreignkey')
    op.drop_constraint(None, 'application_clients', type_='foreignkey')
    op.create_foreign_key('application_clients_client_id_fkey', 'application_clients', 'clients', ['client_id'], ['id'])
    op.create_foreign_key('application_clients_application_id_fkey', 'application_clients', 'applications', ['application_id'], ['id'])
    # ### end Alembic commands ###
