"""applications table changed to requests

Revision ID: e318b087e875
Revises: 620816b5b3d6
Create Date: 2024-06-25 16:13:18.877602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e318b087e875'
down_revision: Union[str, None] = '620816b5b3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('passport', sa.String(), nullable=True),
    sa.Column('issuedby', sa.String(), nullable=True),
    sa.Column('issueddate', sa.DateTime(), nullable=True),
    sa.Column('expireddate', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('pinfl', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_address'), 'clients', ['address'], unique=False)
    op.create_index(op.f('ix_clients_birthdate'), 'clients', ['birthdate'], unique=False)
    op.create_index(op.f('ix_clients_created_at'), 'clients', ['created_at'], unique=False)
    op.create_index(op.f('ix_clients_expireddate'), 'clients', ['expireddate'], unique=False)
    op.create_index(op.f('ix_clients_firstname'), 'clients', ['firstname'], unique=False)
    op.create_index(op.f('ix_clients_gender'), 'clients', ['gender'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_issuedby'), 'clients', ['issuedby'], unique=False)
    op.create_index(op.f('ix_clients_issueddate'), 'clients', ['issueddate'], unique=False)
    op.create_index(op.f('ix_clients_lastname'), 'clients', ['lastname'], unique=False)
    op.create_index(op.f('ix_clients_passport'), 'clients', ['passport'], unique=False)
    op.create_index(op.f('ix_clients_patronymic'), 'clients', ['patronymic'], unique=False)
    op.create_index(op.f('ix_clients_pinfl'), 'clients', ['pinfl'], unique=False)
    op.create_index(op.f('ix_clients_updated_at'), 'clients', ['updated_at'], unique=False)
    op.create_table('application_clients',
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.UniqueConstraint('application_id', 'client_id', name='application_client')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reuqestid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_created_at'), 'requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.create_index(op.f('ix_requests_reuqestid'), 'requests', ['reuqestid'], unique=True)
    op.create_index(op.f('ix_requests_updated_at'), 'requests', ['updated_at'], unique=False)
    op.add_column('applications', sa.Column('departure', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('country', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('datefrom', sa.DateTime(), nullable=True))
    op.add_column('applications', sa.Column('dateto', sa.DateTime(), nullable=True))
    op.add_column('applications', sa.Column('passengers', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('hotel', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('tour', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('status', sa.String(), nullable=True))
    op.drop_index('ix_applications_created_at', table_name='applications')
    op.drop_index('ix_applications_reuqestid', table_name='applications')
    op.drop_index('ix_applications_updated_at', table_name='applications')
    op.create_index(op.f('ix_applications_country'), 'applications', ['country'], unique=False)
    op.create_index(op.f('ix_applications_datefrom'), 'applications', ['datefrom'], unique=False)
    op.create_index(op.f('ix_applications_dateto'), 'applications', ['dateto'], unique=False)
    op.create_index(op.f('ix_applications_departure'), 'applications', ['departure'], unique=False)
    op.create_index(op.f('ix_applications_hotel'), 'applications', ['hotel'], unique=False)
    op.create_index(op.f('ix_applications_passengers'), 'applications', ['passengers'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_tour'), 'applications', ['tour'], unique=False)
    op.drop_constraint('applications_partner_id_fkey', 'applications', type_='foreignkey')
    op.drop_column('applications', 'reuqestid')
    op.drop_column('applications', 'partner_id')
    op.drop_column('applications', 'updated_at')
    op.drop_column('applications', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('reuqestid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('applications_partner_id_fkey', 'applications', 'partners', ['partner_id'], ['id'])
    op.drop_index(op.f('ix_applications_tour'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_passengers'), table_name='applications')
    op.drop_index(op.f('ix_applications_hotel'), table_name='applications')
    op.drop_index(op.f('ix_applications_departure'), table_name='applications')
    op.drop_index(op.f('ix_applications_dateto'), table_name='applications')
    op.drop_index(op.f('ix_applications_datefrom'), table_name='applications')
    op.drop_index(op.f('ix_applications_country'), table_name='applications')
    op.create_index('ix_applications_updated_at', 'applications', ['updated_at'], unique=False)
    op.create_index('ix_applications_reuqestid', 'applications', ['reuqestid'], unique=True)
    op.create_index('ix_applications_created_at', 'applications', ['created_at'], unique=False)
    op.drop_column('applications', 'status')
    op.drop_column('applications', 'tour')
    op.drop_column('applications', 'hotel')
    op.drop_column('applications', 'passengers')
    op.drop_column('applications', 'dateto')
    op.drop_column('applications', 'datefrom')
    op.drop_column('applications', 'country')
    op.drop_column('applications', 'departure')
    op.drop_index(op.f('ix_requests_updated_at'), table_name='requests')
    op.drop_index(op.f('ix_requests_reuqestid'), table_name='requests')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_created_at'), table_name='requests')
    op.drop_table('requests')
    op.drop_table('application_clients')
    op.drop_index(op.f('ix_clients_updated_at'), table_name='clients')
    op.drop_index(op.f('ix_clients_pinfl'), table_name='clients')
    op.drop_index(op.f('ix_clients_patronymic'), table_name='clients')
    op.drop_index(op.f('ix_clients_passport'), table_name='clients')
    op.drop_index(op.f('ix_clients_lastname'), table_name='clients')
    op.drop_index(op.f('ix_clients_issueddate'), table_name='clients')
    op.drop_index(op.f('ix_clients_issuedby'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_gender'), table_name='clients')
    op.drop_index(op.f('ix_clients_firstname'), table_name='clients')
    op.drop_index(op.f('ix_clients_expireddate'), table_name='clients')
    op.drop_index(op.f('ix_clients_created_at'), table_name='clients')
    op.drop_index(op.f('ix_clients_birthdate'), table_name='clients')
    op.drop_index(op.f('ix_clients_address'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
