"""partner relashion added

Revision ID: ea1bb9e9f4a2
Revises: 80b795b9f0d2
Create Date: 2024-06-27 11:06:23.452065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1bb9e9f4a2'
down_revision: Union[str, None] = '80b795b9f0d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
