"""on delete cascade

Revision ID: fb7ad862d12c
Revises: 7485046c8812
Create Date: 2024-06-26 15:46:06.821500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7ad862d12c'
down_revision: Union[str, None] = '7485046c8812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('api_keys_partner_id_fkey', 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'partners', ['partner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('applications_partner_id_fkey', 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'partners', ['partner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key('applications_partner_id_fkey', 'applications', 'partners', ['partner_id'], ['id'])
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key('api_keys_partner_id_fkey', 'api_keys', 'partners', ['partner_id'], ['id'])
    # ### end Alembic commands ###
